DROP DATABASE IF EXISTS COW_WASH;
CREATE DATABASE COW_WASH;
USE COW_WASH;

DROP USER IF EXISTS 'cowwash'@'localhost';
CREATE USER 'cowwash'@'localhost' IDENTIFIED BY '123456';
GRANT SELECT, INSERT, UPDATE, DELETE ON COW_WASH.* TO 'cowwash'@'localhost';

CREATE TABLE ESTADO
(
    ESTA_ID_ESTADO      INT         NOT NULL    AUTO_INCREMENT,
    ESTA_TX_DESCRICAO   VARCHAR(7)  NOT NULL,
    PRIMARY KEY (ESTA_ID_ESTADO)
);

CREATE TABLE VALVULA
(
    VALV_ID_VALVULA     INT         NOT NULL    AUTO_INCREMENT,
    VALV_NU_PERIODO     INT         NOT NULL,
    VALV_DT_REGISTRO    DATETIME    NOT NULL,
    ESTA_ID_ESTADO      INT         NOT NULL,
    PRIMARY KEY (VALV_ID_VALVULA),
    FOREIGN KEY (ESTA_ID_ESTADO) REFERENCES ESTADO(ESTA_ID_ESTADO)
);