USE COW_WASH;

INSERT INTO ESTADO(ESTA_TX_DESCRICAO)
VALUES ('ABERTO');
INSERT INTO ESTADO(ESTA_TX_DESCRICAO)
VALUES ('FECHADO');

-- INSERT INTO VALVULA(VALV_NU_PERIODO, VALV_DT_REGISTRO, ESTA_ID_ESTADO) VALUES (50, NOW(), 1);